apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes
  labels:
    app: probes
spec:
  selector:
    matchLabels:
      app: probes
  replicas: 4
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
        - name: probes
          image: gcr.io/mmatejczyk-gke-dev/probes:v0.0.1
          args:
            - --metric-bind-address=:8080
            - --mode=dnslookup
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: probes
  labels:
    app: probes
spec:
  ports:
    - name: metrics
      port: 8080
  selector:
    app: probes
