apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: headless-service-with-selector
  labels:
    my-label: my-value
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
  selector:
    my-label: my-value
